name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  terraform:
    name: Apply Terraform Configuration
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1  # Adjust region as needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Verify Terraform Installation
        run: |
          terraform --version
          which terraform

      - name: Debug AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID is set: ${AWS_ACCESS_KEY_ID:+true}"
          echo "AWS_SECRET_ACCESS_KEY is set: ${AWS_SECRET_ACCESS_KEY:+true}"
          aws sts get-caller-identity || echo "AWS credentials are invalid or misconfigured"

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate

      - name: Plan Terraform Changes
        run: terraform plan

      - name: Apply Terraform Changes (Auto-Approve)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
